---
- name: Elk Configuration
  hosts: elk
  remote_user: azureuser
  become: True
  tasks:
    - name: Increase Virtual Memory
      command: sysctl -w vm.max_map_count=262144
    - name: Use more memory
      sysctl:
            name: vm.max_map_count
            value: 262144
            state: present
            reload: yes
    - name: docker installation
      apt:
            force_apt_get: yes
            update_cache: yes
            name: docker.io
            state: present
    - name: pip3 installation
      apt:
            force_apt_get: yes
            name: python3-pip
            state: present
    - name: docker python module installation
      pip:
            name: docker
            state: present
    - name: docker elk container download and launch
      docker_container:
            name: elk
            image: sebp/elk:761
            state: started
            restart_policy: always
            published_ports:
             - "5601:5601"
             - "9200:9200"
             - "5044:5044"